Add `types-requests` to run mypy
Adding `types-requests` to the `dev` dependency group in `pyproject.toml`
to ensure type checking for requests in the development environment.

error found:

```uv run mypy **/*.py --install-types --non-interactive                                               ─╯
Uninstalled 11 packages in 243ms
Installed 11 packages in 80ms
Installing missing stub packages:
/Users/ctw00944-admin/r2s/repos/weather-service/.venv/bin/python3 -m pip install types-requests types-ujson

/Users/ctw00944-admin/r2s/repos/weather-service/.venv/bin/python3: No module named pip

exporter/metrics_exporter.py:5: error: Library stubs not installed for "requests"  [import-untyped]
exporter/metrics_exporter.py:5: note: Hint: "python3 -m pip install types-requests"
exporter/metrics_exporter.py:5: note: (or run "mypy --install-types" to install all missing stub packages)
exporter/metrics_exporter.py:5: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 12 source files)

````

tested:
```uv run black . && uv run ruff check --fix --exit-non-zero-on-fix && uv run mypy **/*.py --install-types --non-interactive
All done! ✨ 🍰 ✨
12 files left unchanged.
All checks passed!
Installing missing stub packages:
/Users/ctw00944-admin/r2s/repos/weather-service/.venv/bin/python3 -m pip install types-ujson

/Users/ctw00944-admin/r2s/repos/weather-service/.venv/bin/python3: No module named pip

Success: no issues found in 12 source files

```