Fix mypy error on check pipeline
error:

```
LOG:  Found 242 SCCs; largest has 58 nodes
LOG:  Processing 239 queued fresh SCCs
LOG:  Processing SCC singleton (app.services.weather_services) as inherently stale
LOG:  Deleting app.services.weather_services /home/runner/work/weather-service/weather-service/app/services/weather_services.py app/services/weather_services.meta.json app/services/weather_services.data.json
LOG:  Processing SCC singleton (app.api.v1.routes) as inherently stale with stale deps (app.services.weather_services)
LOG:  Deleting app.api.v1.routes /home/runner/work/weather-service/weather-service/app/api/v1/routes.py app/api/v1/routes.meta.json app/api/v1/routes.data.json
LOG:  Processing SCC singleton (app.main) as inherently stale with stale deps (app.api.v1.routes)
LOG:  Deleting app.main app/main.py app/main.meta.json app/main.data.json
LOG:  No fresh SCCs left in queue
LOG:  Build finished in 0.866 seconds with 475 modules, and 2 errors
app/services/weather_services.py:11: error: Cannot find implementation or library stub for module named "app.services.redis"  [import-not-found]
app/services/weather_services.py:11: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Installing missing stub packages:
/home/runner/work/weather-service/weather-service/.venv/bin/python3 -m pip install types-Pygments types-ujson

Found 1 error in 1 file (checked 2 source files)
Error: Process completed with exit code 1.
```